#!/bin/sh
args=""
while [ $# -gt 0 ]; do
  case "$1" in
    -Wl,--version-script|-Wl,--dynamic-list)
      flag="$1"; shift
      args="$args $flag=$1"
      ;;
    *)
      args="$args $1"
      ;;
  esac
  shift
done
# shellcheck disable=SC2086
exec zig c++ -target x86_64-linux-musl $args
