#!/usr/bin/env python3
"""gen-defkeymap.py <defkeymap.c> > servers/tty/src/defkeymap.rs

Turn the C tables `loadkeys --mktable defkeymap.map` prints (kbd; the same
generator Linux uses for drivers/tty/vt/defkeymap.c_shipped) into the Rust
constants the VT keyboard starts from. Values are converted from the kernel's
stored form U(v) = v ^ 0xf000 back to the KDGKBENT/KDSKBENT form, which is
what servers/tty/src/keyboard.rs keeps.
"""
import re, sys

src = open(sys.argv[1]).read()
order = re.search(r"key_maps\[MAX_NR_KEYMAPS\] = \{(.*?)\};", src, re.S).group(1)
names = [n.strip() for n in order.replace("\n", " ").split(",") if n.strip() and n.strip() != "0"]
maps = []
for n in names:
    body = re.search(rf"{n}\[NR_KEYS\] = \{{(.*?)\}};", src, re.S).group(1)
    vals = [int(x, 16) ^ 0xF000 for x in re.findall(r"0x[0-9a-f]+", body)]
    assert len(vals) == 256, (n, len(vals))
    maps.append((n, vals))

def cchar(tok):
    tok = tok.strip()
    assert tok[0] == "'" and tok[-1] == "'", tok
    t = tok[1:-1]
    if t.startswith("\\"):
        if t[1:].isdigit():
            return int(t[1:], 8)
        return {"\\'": 39, '\\"': 34, "\\\\": 92, "\\033": 27}.get(t, ord(t[1]))
    return ord(t)

buf = re.search(r"char func_buf\[\] = \{(.*?)\};", src, re.S).group(1)
items = re.findall(r"'(?:\\.|\\\d+|[^'])+'|\b0\b", buf)
funcs, cur = [], []
for it in items:
    if it == "0":
        funcs.append(bytes(cur)); cur = []
    else:
        cur.append(cchar(it))

acc = re.search(r"accent_table\[MAX_DIACR\] = \{(.*?)\n\};", src, re.S).group(1)
accents = []
for m in re.finditer(r"\{('(?:\\.|\\\d+|[^'])+'),\s*('(?:\\.|\\\d+|[^'])+'),\s*('(?:\\.|\\\d+|[^'])+')\}", acc):
    accents.append(tuple(cchar(g) for g in m.groups()))

out = []
out.append("// @generated by ports/kbd-keymaps/gen-defkeymap.py from the output of")
out.append("// `loadkeys --mktable defkeymap.map` (kbd 2.10.0) — Linux's default console")
out.append("// keymap (drivers/tty/vt/defkeymap.map). Do not edit by hand.")
out.append("//")
out.append("// Keysyms are in KDGKBENT form (KTYP << 8 | KVAL), not the kernel's stored")
out.append("// U() form. Map index = shift state: Shift 1, AltGr 2, Ctrl 4, Alt 8.")
out.append("")
out.append(f"pub const DEFAULT_KEYMAP: [[u16; 256]; {len(maps)}] = [")
for n, vals in maps:
    out.append(f"    // {n}")
    out.append("    [")
    for i in range(0, 256, 8):
        out.append("        " + " ".join(f"0x{v:04x}," for v in vals[i:i+8]))
    out.append("    ],")
out.append("];")
out.append("")
out.append(f"/// Default function-key strings (KT_FN), `func_table[0..{len(funcs)}]`.")
out.append(f"pub const DEFAULT_FUNC: [&[u8]; {len(funcs)}] = [")
for f in funcs:
    out.append("    b\"" + "".join(f"\\x{b:02x}" for b in f) + "\",")
out.append("];")
out.append("")
out.append("/// Default dead-key compositions: (diacritic, base, result), Latin-1.")
out.append(f"pub const DEFAULT_ACCENTS: [(u8, u8, u8); {len(accents)}] = [")
for a in accents:
    out.append(f"    (0x{a[0]:02x}, 0x{a[1]:02x}, 0x{a[2]:02x}),")
out.append("];")
print("\n".join(out))
