[package]
name = "f2fs-server"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[features]
rpi5 = ["drivers/rpi5"]
raspi4b = ["drivers/raspi4b"]

[dependencies]
ipc     = { path = "../../ipc" }
sched   = { path = "../../sched" }
mm      = { path = "../../mm" }
drivers = { path = "../../drivers" }
spin    = "0.9"
vfs-server = { path = "../vfs" }
xattr   = { path = "../xattr" }
