[workspace]
resolver = "2"
members = ["libc", "hello", "shell", "init", "aplay", "memtest", "vfstest", "f2fstest", "pthreadtest", "timertest", "sigtest", "polltest", "forktest", "racetest"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
strip = false
